/**
 * Synthetic demo invoices. Fictional vendors only — safe for screenshots,
 * portfolios, and exploring the UI without uploading real documents.
 */

export const DEMO_INVOICES = [
  {
    supplier: 'Acme Office Supply Co.',
    invoice_number: 'ACM-2026-1042',
    invoice_date: '2026-08-14',
    due_date: '2026-09-13',
    currency: 'USD',
    subtotal: 486.0,
    tax: 38.88,
    tax_rate: 8,
    total: 524.88,
    purchase_order: 'PO-7781',
    payment_terms: 'Net 30',
    confidence: 94,
    status: 'needs_review',
    validation_flags: [],
    raw_ocr_text: 'Acme Office Supply Co.\nInvoice ACM-2026-1042\nDate: 2026-08-14  Due: 2026-09-13\nSubtotal $486.00  Tax $38.88  Total $524.88',
    line_items: [
      { description: 'Ergonomic office chair', quantity: 2, unit_price: 189.0, tax: 30.24, total: 378.0 },
      { description: 'Standing desk converter', quantity: 1, unit_price: 108.0, tax: 8.64, total: 108.0 },
    ],
  },
  {
    supplier: 'Northwind Cloud Services',
    invoice_number: 'NW-88190',
    invoice_date: '2026-08-28',
    due_date: '2026-09-28',
    currency: 'USD',
    subtotal: 1299.0,
    tax: 0,
    tax_rate: 0,
    total: 1299.0,
    purchase_order: null,
    payment_terms: 'Due on receipt',
    confidence: 88,
    status: 'approved',
    validation_flags: [],
    raw_ocr_text: 'Northwind Cloud Services\nInvoice NW-88190\nCompute + storage, August 2026\nTotal $1,299.00',
    line_items: [
      { description: 'Compute credits — August', quantity: 1, unit_price: 899.0, tax: 0, total: 899.0 },
      { description: 'Object storage 12 TB', quantity: 1, unit_price: 400.0, tax: 0, total: 400.0 },
    ],
  },
  {
    supplier: 'Contoso Freight Ltd.',
    invoice_number: 'CF-55621',
    invoice_date: '2026-07-30',
    due_date: null,
    currency: 'EUR',
    subtotal: 740.0,
    tax: 140.6,
    tax_rate: 19,
    total: 880.6,
    purchase_order: 'PO-7719',
    payment_terms: 'Net 14',
    confidence: 52,
    status: 'needs_review',
    validation_flags: ['LOW_CONFIDENCE', 'OCR_UNCERTAIN'],
    raw_ocr_text: 'C0ntos0 Freight Lt...\nInv CF-55621 (scan smudged)\nSubt0tal 740.00 T0tal 880.60',
    line_items: [{ description: 'Pallet freight — Hamburg to Prague (illegible surcharge line)', quantity: 4, unit_price: 185.0, tax: null, total: 740.0 }],
  },
  {
    supplier: 'Acme Office Supply Co.',
    invoice_number: 'ACM-2026-1042',
    invoice_date: '2026-08-14',
    due_date: '2026-09-13',
    currency: 'USD',
    subtotal: 486.0,
    tax: 38.88,
    tax_rate: 8,
    total: 524.88,
    purchase_order: 'PO-7781',
    payment_terms: 'Net 30',
    confidence: 91,
    status: 'needs_review',
    validation_flags: ['POSSIBLE_DUPLICATE'],
    raw_ocr_text: 'Acme Office Supply Co. (rescan)\nInvoice ACM-2026-1042\nPossible duplicate of earlier upload.',
    line_items: [
      { description: 'Ergonomic office chair', quantity: 2, unit_price: 189.0, tax: 30.24, total: 378.0 },
      { description: 'Standing desk converter', quantity: 1, unit_price: 108.0, tax: 8.64, total: 108.0 },
    ],
  },
  {
    supplier: 'Fabrikam Design Studio',
    invoice_number: 'FAB-2031',
    invoice_date: '2026-06-02',
    due_date: '2026-07-02',
    currency: 'GBP',
    subtotal: 2400.0,
    tax: 480.0,
    tax_rate: 20,
    total: 2880.0,
    purchase_order: null,
    payment_terms: 'Net 30',
    confidence: 97,
    status: 'rejected',
    validation_flags: ['TOTAL_MISMATCH'],
    raw_ocr_text: 'Fabrikam Design Studio\nInvoice FAB-2031\nBrand refresh milestone 2\nQuoted total differs from line sum — rejected pending correction.',
    line_items: [
      { description: 'Brand refresh milestone 2', quantity: 1, unit_price: 2400.0, tax: 480.0, total: 2880.0 },
      { description: 'Rush fee (disputed)', quantity: 1, unit_price: 150.0, tax: 30.0, total: 180.0 },
    ],
  },
  {
    supplier: 'Globex Hardware',
    invoice_number: '',
    invoice_date: '',
    due_date: null,
    currency: '',
    subtotal: null,
    tax: null,
    tax_rate: null,
    total: null,
    purchase_order: null,
    payment_terms: null,
    confidence: 22,
    status: 'needs_review',
    validation_flags: ['MISSING_INVOICE_NUMBER', 'MISSING_SUPPLIER', 'MISSING_DATE', 'MISSING_TOTAL', 'LOW_CONFIDENCE', 'AI_EXTRACTION_UNCERTAIN'],
    raw_ocr_text: '(coffee-stained thermal receipt, mostly unreadable)',
    line_items: [],
  },
];

export function buildDemoRows(userId) {
  const now = new Date();
  return DEMO_INVOICES.map((d, i) => ({
    user_id: userId,
    file_path: null,
    original_filename: `demo-invoice-${i + 1}.pdf`,
    supplier: d.supplier,
    invoice_number: d.invoice_number,
    invoice_date: d.invoice_date || null,
    due_date: d.due_date || null,
    currency: d.currency,
    subtotal: d.subtotal,
    tax: d.tax,
    tax_rate: d.tax_rate,
    total: d.total,
    purchase_order: d.purchase_order,
    payment_terms: d.payment_terms,
    raw_ocr_text: d.raw_ocr_text,
    ai_extraction: {
      supplier: d.supplier,
      invoice_number: d.invoice_number,
      invoice_date: d.invoice_date,
      due_date: d.due_date,
      currency: d.currency,
      subtotal: d.subtotal,
      tax: d.tax,
      tax_rate: d.tax_rate,
      total: d.total,
      purchase_order: d.purchase_order,
      payment_terms: d.payment_terms,
      line_items: d.line_items,
      confidence: d.confidence,
      validation_flags: d.validation_flags,
    },
    confidence: d.confidence,
    status: d.status,
    created_at: new Date(now.getTime() - (DEMO_INVOICES.length - i) * 86400000).toISOString(),
  }));
}
